/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEW1.VIEW2.Pax_ctrl;

import CONTROLADOR.DAOTripulacionIMPL;
import Interfaces.DAOTripulacion;
import java.awt.Color;
import VIEW1.Dashboard;
import VIEW1.VIEW2.Pax_control;
import VIEW1.VIEW2.Reportes_vuelos;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samsung
 */
public class Ver_Tripulacion extends javax.swing.JPanel {

    /**
     * Creates new form Hora_abordaje
     */
    public Ver_Tripulacion() {
        initComponents();
        tableAzafatas.setDefaultEditor(Object.class, null);
        tablePilotos.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbidT = new javax.swing.JLabel();
        lb_back = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePilotos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAzafatas = new javax.swing.JTable();
        bt_borrarA = new javax.swing.JButton();
        bt_borrarP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        lbidT.setForeground(new java.awt.Color(0, 0, 0));
        lbidT.setText("Id Tripulacion: ");

        lb_back.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        lb_back.setForeground(new java.awt.Color(102, 102, 102));
        lb_back.setText("x");
        lb_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_backMouseExited(evt);
            }
        });

        tablePilotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo P.", "Nombre", "Apellido", "Documento", "Jerarquiá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablePilotos.setMaximumSize(new java.awt.Dimension(60, 64));
        jScrollPane1.setViewportView(tablePilotos);

        tableAzafatas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo A.", "Nombre", "Apellido", "Documento", "Jerarquía"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAzafatas.setMaximumSize(new java.awt.Dimension(60, 64));
        jScrollPane2.setViewportView(tableAzafatas);

        bt_borrarA.setText("Borrar");
        bt_borrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_borrarAActionPerformed(evt);
            }
        });

        bt_borrarP.setText("Borrar");
        bt_borrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_borrarPActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Pilotos  -->");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Azafatas  -->");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tripulación");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_borrarP)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(lbidT, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lb_back, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_borrarA)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbidT)
                            .addComponent(jLabel4)))
                    .addComponent(lb_back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_borrarP)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_borrarA)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void listarPilotos(int idT){
        try {
            DAOTripulacion dao = new DAOTripulacionIMPL();
            DefaultTableModel modelP = (DefaultTableModel) tablePilotos.getModel();
            modelP.setRowCount(0);
            dao.getTripulacionById(idT).getListaPiloto().forEach((pi)->modelP.addRow(new Object[]{pi.getCodigo(), pi.getNombre(), pi.getApellido(), pi.getDocumentos(), pi.getJerarquia()}));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void listarAzafatas(int idT){
        try {
            DAOTripulacion daoT = new DAOTripulacionIMPL();
            DefaultTableModel modelA = (DefaultTableModel) tableAzafatas.getModel();
            modelA.setRowCount(0);
            daoT.getTripulacionById(idT).getListaAzafata().forEach((az)->modelA.addRow(new Object[]{az.getCodigo(),az.getNombre(),az.getApellido(), az.getDocumentos(), az.getJerarquia()}));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void lb_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseClicked
    }//GEN-LAST:event_lb_backMouseClicked

    private void lb_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseEntered
        lb_back.setForeground(Color.BLACK);
    }//GEN-LAST:event_lb_backMouseEntered

    private void lb_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseExited
        lb_back.setForeground(new Color(191,191,191));
    }//GEN-LAST:event_lb_backMouseExited

    private void bt_borrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_borrarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_borrarAActionPerformed

    private void bt_borrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_borrarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_borrarPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bt_borrarA;
    public javax.swing.JButton bt_borrarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lb_back;
    public javax.swing.JLabel lbidT;
    public javax.swing.JTable tableAzafatas;
    public javax.swing.JTable tablePilotos;
    // End of variables declaration//GEN-END:variables
}
