/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;
import VIEW1.Dashboard;
import java.awt.Color;
/**
 *
 * @author Samsung
 */
public class login extends javax.swing.JFrame {

    int ejex, ejey;
    public String user, password;
    public login() {
        initComponents();
        bt_login.requestFocusInWindow();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        logo3 = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        panel_bt_exit = new javax.swing.JPanel();
        bt_exit = new javax.swing.JLabel();
        image_font = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        iniciar_sesion = new javax.swing.JLabel();
        label_u = new javax.swing.JLabel();
        txt_enter_user = new javax.swing.JTextField();
        separator = new javax.swing.JSeparator();
        label_c = new javax.swing.JLabel();
        separator2 = new javax.swing.JSeparator();
        txt_enter_password = new javax.swing.JPasswordField();
        bt_login = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginFocusLost(evt);
            }
        });
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo3.png"))); // NOI18N
        login.add(logo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 70, 100));

        logo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo2_1.png"))); // NOI18N
        login.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 100, 80));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setOpaque(false);
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        panel_bt_exit.setBackground(new java.awt.Color(255, 0, 0));
        panel_bt_exit.setToolTipText("");
        panel_bt_exit.setFocusable(false);
        panel_bt_exit.setOpaque(false);
        panel_bt_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_bt_exitMouseExited(evt);
            }
        });

        bt_exit.setBackground(new java.awt.Color(255, 255, 255));
        bt_exit.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        bt_exit.setForeground(new java.awt.Color(0, 0, 0));
        bt_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_exit.setText("X");
        bt_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_exit.setVerifyInputWhenFocusTarget(false);
        bt_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_bt_exitLayout = new javax.swing.GroupLayout(panel_bt_exit);
        panel_bt_exit.setLayout(panel_bt_exitLayout);
        panel_bt_exitLayout.setHorizontalGroup(
            panel_bt_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_bt_exitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_bt_exitLayout.setVerticalGroup(
            panel_bt_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bt_exitLayout.createSequentialGroup()
                .addComponent(bt_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(0, 760, Short.MAX_VALUE)
                .addComponent(panel_bt_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(panel_bt_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        login.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        image_font.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cover spanish_1.jpg"))); // NOI18N
        login.add(image_font, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 360, 500));

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo1.png"))); // NOI18N
        login.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 270, 80));

        iniciar_sesion.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        iniciar_sesion.setForeground(new java.awt.Color(0, 0, 0));
        iniciar_sesion.setText("INICIAR SESIÓN ");
        iniciar_sesion.setToolTipText("");
        login.add(iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        label_u.setBackground(new java.awt.Color(255, 255, 255));
        label_u.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        label_u.setForeground(new java.awt.Color(0, 0, 0));
        label_u.setText("USUARIO");
        login.add(label_u, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 150, 20));

        txt_enter_user.setBackground(new java.awt.Color(255, 255, 255));
        txt_enter_user.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 16)); // NOI18N
        txt_enter_user.setForeground(new java.awt.Color(204, 204, 204));
        txt_enter_user.setText("Ingrese sú nombre de usuario");
        txt_enter_user.setBorder(null);
        txt_enter_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_enter_userMousePressed(evt);
            }
        });
        txt_enter_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_userActionPerformed(evt);
            }
        });
        login.add(txt_enter_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 360, 40));

        separator.setBackground(new java.awt.Color(0, 0, 0));
        login.add(separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 360, 30));

        label_c.setBackground(new java.awt.Color(255, 255, 255));
        label_c.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        label_c.setForeground(new java.awt.Color(0, 0, 0));
        label_c.setText("CONTRASEÑA");
        login.add(label_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 150, 20));

        separator2.setBackground(new java.awt.Color(0, 0, 0));
        login.add(separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 360, 30));

        txt_enter_password.setBackground(new java.awt.Color(255, 255, 255));
        txt_enter_password.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_enter_password.setForeground(new java.awt.Color(204, 204, 204));
        txt_enter_password.setText("**********");
        txt_enter_password.setBorder(null);
        txt_enter_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_enter_passwordMousePressed(evt);
            }
        });
        txt_enter_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_passwordActionPerformed(evt);
            }
        });
        login.add(txt_enter_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 360, 40));

        bt_login.setBackground(new java.awt.Color(139, 169, 197));
        bt_login.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        bt_login.setForeground(new java.awt.Color(255, 255, 255));
        bt_login.setText("LOGIN");
        bt_login.setBorder(null);
        bt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_loginMouseExited(evt);
            }
        });
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });
        login.add(bt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFocusGained

    private void loginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFocusLost

    private void txt_enter_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_userActionPerformed

    private void txt_enter_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_passwordActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        ejex = evt.getX();
        ejey = evt.getY();

    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - ejex, y - ejey);
    }//GEN-LAST:event_headerMouseDragged

    private void bt_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_bt_exitMouseClicked

    private void bt_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_exitMouseEntered
        panel_bt_exit.setBackground(Color.red);
        panel_bt_exit.setOpaque(true);
        bt_exit.setForeground(Color.white);
    }//GEN-LAST:event_bt_exitMouseEntered

    private void bt_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_exitMouseExited
        panel_bt_exit.setOpaque(false);
        bt_exit.setForeground(Color.black);
    }//GEN-LAST:event_bt_exitMouseExited

    private void panel_bt_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_bt_exitMouseExited
         // codificar
    }//GEN-LAST:event_panel_bt_exitMouseExited

    private void txt_enter_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_enter_userMousePressed
        if(txt_enter_user.getText().equals("Ingrese sú nombre de usuario")|| txt_enter_user.getText().isEmpty()){
            txt_enter_user.setText("");
            txt_enter_user.setForeground(Color.black);}
        
        if (txt_enter_password.getText().isEmpty()){
            txt_enter_password.setForeground(new Color(204,204,204));        
            txt_enter_password.setText("**********");}
    }//GEN-LAST:event_txt_enter_userMousePressed

    private void txt_enter_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_enter_passwordMousePressed
        if (String.valueOf(txt_enter_password.getPassword()).equals("**********") || String.valueOf(txt_enter_password.getPassword()).isEmpty()){
            txt_enter_password.setText("");
            txt_enter_password.setForeground(Color.black);}

        if(txt_enter_user.getText().isEmpty()){
                txt_enter_user.setForeground(new Color(204,204,204));        
                txt_enter_user.setText("Ingrese sú nombre de usuario");}
    }//GEN-LAST:event_txt_enter_passwordMousePressed

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
      
    }//GEN-LAST:event_bt_loginActionPerformed

    private void bt_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseEntered
        bt_login.setBackground(new Color(83,102,132));
    }//GEN-LAST:event_bt_loginMouseEntered

    private void bt_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseExited
        bt_login.setBackground(new Color(139,169,197));
    }//GEN-LAST:event_bt_loginMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_exit;
    public javax.swing.JButton bt_login;
    private javax.swing.JPanel header;
    private javax.swing.JLabel image_font;
    private javax.swing.JLabel iniciar_sesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label_c;
    private javax.swing.JLabel label_u;
    public javax.swing.JPanel login;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel logo3;
    private javax.swing.JPanel panel_bt_exit;
    private javax.swing.JSeparator separator;
    private javax.swing.JSeparator separator2;
    public javax.swing.JPasswordField txt_enter_password;
    public javax.swing.JTextField txt_enter_user;
    // End of variables declaration//GEN-END:variables
}
