package VIEW1.VIEW2;

import MODELS.Pasaje;
import MODELS.Pasajeros;
import VIEW1.Dashboard;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Samsung
 */
public class Administracion_pasajero extends javax.swing.JPanel {
    public int pasajeroId;
    public Pasajeros pasajero;
    /**
     * Creates new form Principal
     */
    public Administracion_pasajero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        documentotxt = new javax.swing.JTextField();
        bt_verificar = new javax.swing.JButton();
        idPasajetxt = new javax.swing.JTextField();
        codigoVtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SP = new javax.swing.JToggleButton();
        bgSV = new javax.swing.JPanel();
        bt_descartarSV = new javax.swing.JButton();
        lbsv = new javax.swing.JLabel();
        bgSERVICES = new javax.swing.JPanel();
        bt_mascota_cabina = new javax.swing.JToggleButton();
        bt_mascota = new javax.swing.JToggleButton();
        bt_diacapacidad = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        lb_back = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bgEquipaje = new javax.swing.JPanel();
        lbpeso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbdimensiones = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbaltura = new javax.swing.JLabel();
        lbancho = new javax.swing.JLabel();
        lblongitud = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bt_Maleta = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(710, 403));
        setPreferredSize(new java.awt.Dimension(710, 403));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(710, 403));
        bg.setPreferredSize(new java.awt.Dimension(710, 390));

        tittle.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        tittle.setForeground(new java.awt.Color(0, 0, 0));
        tittle.setText("Pasajero ");

        bt_verificar.setText("Verificar");
        bt_verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_verificarActionPerformed(evt);
            }
        });

        codigoVtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoVtxtActionPerformed(evt);
            }
        });

        jLabel6.setText("Codigo Vuelo");

        jLabel7.setText("Documento");

        jLabel8.setText("Id Pasaje");

        jLabel9.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Verificar datos");

        SP.setBackground(new java.awt.Color(255, 0, 0));
        SP.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        SP.setText("NO  |");
        SP.setBorderPainted(false);
        SP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPActionPerformed(evt);
            }
        });

        bgSV.setMaximumSize(new java.awt.Dimension(360, 200));

        bt_descartarSV.setText("Descartar Servicios Especiales");
        bt_descartarSV.setMaximumSize(new java.awt.Dimension(185, 100));
        bt_descartarSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_descartarSVActionPerformed(evt);
            }
        });

        lbsv.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        lbsv.setForeground(new java.awt.Color(0, 0, 0));
        lbsv.setText("¿Descartar serviciós especiales? ");

        bgSERVICES.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        bgSERVICES.setMaximumSize(new java.awt.Dimension(1000, 800));
        bgSERVICES.setLayout(new java.awt.GridLayout(2, 2));

        bt_mascota_cabina.setText("Mascota en cabina");
        bgSERVICES.add(bt_mascota_cabina);

        bt_mascota.setText("Mascota");
        bgSERVICES.add(bt_mascota);

        bt_diacapacidad.setText("Discapacidad");
        bt_diacapacidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_diacapacidadMouseClicked(evt);
            }
        });
        bt_diacapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_diacapacidadActionPerformed(evt);
            }
        });
        bgSERVICES.add(bt_diacapacidad);

        javax.swing.GroupLayout bgSVLayout = new javax.swing.GroupLayout(bgSV);
        bgSV.setLayout(bgSVLayout);
        bgSVLayout.setHorizontalGroup(
            bgSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgSVLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(bgSERVICES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bgSVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbsv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgSVLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(bt_descartarSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );
        bgSVLayout.setVerticalGroup(
            bgSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgSVLayout.createSequentialGroup()
                .addComponent(bgSERVICES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbsv, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_descartarSV, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("¿Servicios Especiales? ");

        lb_back.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        lb_back.setForeground(new java.awt.Color(191, 191, 191));
        lb_back.setText("<<<");
        lb_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_backMouseExited(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lbpeso.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        lbpeso.setForeground(new java.awt.Color(102, 102, 102));
        lbpeso.setText("Peso: ");

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Equipaje");

        lbdimensiones.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        lbdimensiones.setForeground(new java.awt.Color(102, 102, 102));
        lbdimensiones.setText("Dimensiones: ");

        lbaltura.setBackground(new java.awt.Color(255, 255, 255));
        lbaltura.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        lbaltura.setForeground(new java.awt.Color(0, 0, 0));
        lbaltura.setText("Alto: N/A");
        lbaltura.setOpaque(true);

        lbancho.setBackground(new java.awt.Color(255, 255, 255));
        lbancho.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        lbancho.setForeground(new java.awt.Color(0, 0, 0));
        lbancho.setText("Ancho: N/A");
        lbancho.setOpaque(true);

        lblongitud.setBackground(new java.awt.Color(255, 255, 255));
        lblongitud.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        lblongitud.setForeground(new java.awt.Color(0, 0, 0));
        lblongitud.setText("Longitud: N/A");
        lblongitud.setOpaque(true);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maleta (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(lbaltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblongitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(140, 140, 140))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(lbancho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lbaltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100)
                .addComponent(lblongitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(lbancho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bt_Maleta.setText("Asignar Nueva Maleta");
        bt_Maleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_MaletaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgEquipajeLayout = new javax.swing.GroupLayout(bgEquipaje);
        bgEquipaje.setLayout(bgEquipajeLayout);
        bgEquipajeLayout.setHorizontalGroup(
            bgEquipajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgEquipajeLayout.createSequentialGroup()
                .addGroup(bgEquipajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgEquipajeLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(67, 67, 67))
                    .addGroup(bgEquipajeLayout.createSequentialGroup()
                        .addComponent(lbpeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgEquipajeLayout.createSequentialGroup()
                        .addComponent(lbdimensiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(bgEquipajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgEquipajeLayout.createSequentialGroup()
                        .addComponent(bt_Maleta, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        bgEquipajeLayout.setVerticalGroup(
            bgEquipajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgEquipajeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(lbpeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(69, 69, 69)
                .addComponent(lbdimensiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(65, 65, 65))
            .addGroup(bgEquipajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_Maleta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(codigoVtxt)
                        .addGap(42, 42, 42))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lb_back, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(bt_verificar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(documentotxt)
                    .addComponent(idPasajetxt))
                .addGap(102, 102, 102))
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(bgSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bgEquipaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(tittle)
                        .addGap(22, 22, 22)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(codigoVtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(bt_verificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(documentotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(idPasajetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jSeparator1)
                                .addGap(3, 3, 3))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bgSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bgEquipaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        bgSV.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_verificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_verificarActionPerformed
    public void showJPanel(JPanel p1){  
       bgSV.setLayout(new BorderLayout());
       bgSV.removeAll();
       bgSV.add(p1, BorderLayout.CENTER);
       bgSV.revalidate();
       bgSV.repaint();
    }
    private void SPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPActionPerformed
        
    }//GEN-LAST:event_SPActionPerformed

    private void bt_descartarSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_descartarSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_descartarSVActionPerformed

    private void lb_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseClicked
    }//GEN-LAST:event_lb_backMouseClicked

    private void lb_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseEntered
        lb_back.setForeground(Color.BLACK);
    }//GEN-LAST:event_lb_backMouseEntered

    private void lb_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseExited
        lb_back.setForeground(new Color(191,191,191));
    }//GEN-LAST:event_lb_backMouseExited

    private void bt_diacapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_diacapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_diacapacidadActionPerformed

    private void bt_diacapacidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_diacapacidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_diacapacidadMouseClicked

    private void codigoVtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoVtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoVtxtActionPerformed

    private void bt_MaletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_MaletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_MaletaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton SP;
    public javax.swing.JPanel bg;
    private javax.swing.JPanel bgEquipaje;
    public javax.swing.JPanel bgSERVICES;
    public javax.swing.JPanel bgSV;
    public javax.swing.JButton bt_Maleta;
    public javax.swing.JButton bt_descartarSV;
    public javax.swing.JToggleButton bt_diacapacidad;
    public javax.swing.JToggleButton bt_mascota;
    public javax.swing.JToggleButton bt_mascota_cabina;
    public javax.swing.JButton bt_verificar;
    public javax.swing.JTextField codigoVtxt;
    public javax.swing.JTextField documentotxt;
    public javax.swing.JTextField idPasajetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lb_back;
    public javax.swing.JLabel lbaltura;
    public javax.swing.JLabel lbancho;
    private javax.swing.JLabel lbdimensiones;
    public javax.swing.JLabel lblongitud;
    public javax.swing.JLabel lbpeso;
    public javax.swing.JLabel lbsv;
    public javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
