package VIEW1.VIEW2;

import CONTROLADOR.DAOVuelosIMPL;
import Interfaces.DAOVuelos;
import VIEW1.Dashboard;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Samsung
 */
public class Reportes_vuelos extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Reportes_vuelos() {
        initComponents();
        tabla_vuelos.setDefaultEditor(Object.class, null);
        barra_busqueda.putClientProperty("JTextField.placeholderText", "Ingrese el codigo del vuelo a buscar.");
        listarVuelos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_vuelos = new javax.swing.JLabel();
        barra_busqueda = new javax.swing.JTextField();
        bt_nuevo_vuelo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_vuelos = new javax.swing.JTable();
        bt_search = new javax.swing.JButton();
        bt_borrar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        lb_back = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(710, 403));
        setPreferredSize(new java.awt.Dimension(710, 403));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(710, 403));
        jPanel1.setPreferredSize(new java.awt.Dimension(710, 390));

        txt_vuelos.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        txt_vuelos.setText("Vuelos");

        bt_nuevo_vuelo.setText("Nuevo vuelo");
        bt_nuevo_vuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nuevo_vueloActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tabla_vuelos.setAutoCreateRowSorter(true);
        tabla_vuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Codigo", "Estado", "Origen", "Destino", "Hora Salida", "Hora llegada", "Cantidad de pasajeros", "Id Tripulación", "Avion", "Fecha"
            }
        ));
        tabla_vuelos.setColumnSelectionAllowed(true);
        tabla_vuelos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabla_vuelos.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tabla_vuelos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla_vuelos.setShowGrid(true);
        jScrollPane1.setViewportView(tabla_vuelos);
        tabla_vuelos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tabla_vuelos.getColumnModel().getColumnCount() > 0) {
            tabla_vuelos.getColumnModel().getColumn(0).setMinWidth(25);
            tabla_vuelos.getColumnModel().getColumn(0).setMaxWidth(40);
        }
        tabla_vuelos.getAccessibleContext().setAccessibleName("");

        bt_search.setText("Buscar");
        bt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_searchActionPerformed(evt);
            }
        });

        bt_borrar.setText("Borrar");
        bt_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_borrarActionPerformed(evt);
            }
        });

        bt_editar.setText("Editar");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        lb_back.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        lb_back.setForeground(new java.awt.Color(191, 191, 191));
        lb_back.setText("<<<");
        lb_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_backMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_vuelos, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(463, 463, 463)
                .addComponent(lb_back, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barra_busqueda)
                .addGap(18, 18, 18)
                .addComponent(bt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(bt_nuevo_vuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bt_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_vuelos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barra_busqueda)
                    .addComponent(bt_search, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_nuevo_vuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void listarVuelos(){
        try {
            String name = barra_busqueda.getText();
            DAOVuelos dao = new DAOVuelosIMPL();
            DefaultTableModel model = (DefaultTableModel) tabla_vuelos.getModel();
            model.setRowCount(0);
            dao.listarVU(name).forEach((v)->model.addRow(new Object[]{v.getIdvuelo(),v.getCodigo(),v.getEstado(),
                v.getOrigen(),v.getDestino(), v.getHorasalida(), v.getHorallegada(), v.getCantidadpasajeros(), 
                v.getTripulacion() != null ? v.getTripulacion().getIdtripulacion() : "N/A", v.getAvion() != null? v.getAvion().getIdavion(): "N/A", v.getFecha()}));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void bt_nuevo_vueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nuevo_vueloActionPerformed
    }//GEN-LAST:event_bt_nuevo_vueloActionPerformed

    private void bt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_searchActionPerformed

    private void bt_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_borrarActionPerformed

    }//GEN-LAST:event_bt_borrarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
    
    }//GEN-LAST:event_bt_editarActionPerformed

    private void lb_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseClicked
    }//GEN-LAST:event_lb_backMouseClicked

    private void lb_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseEntered
        lb_back.setForeground(Color.BLACK);
    }//GEN-LAST:event_lb_backMouseEntered

    private void lb_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseExited
        lb_back.setForeground(new Color(191,191,191));
    }//GEN-LAST:event_lb_backMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField barra_busqueda;
    public javax.swing.JButton bt_borrar;
    public javax.swing.JButton bt_editar;
    public javax.swing.JButton bt_nuevo_vuelo;
    public javax.swing.JButton bt_search;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lb_back;
    public javax.swing.JTable tabla_vuelos;
    private javax.swing.JLabel txt_vuelos;
    // End of variables declaration//GEN-END:variables
}
