package VIEW1.VIEW2;

import CONTROLADOR.DAOSVDiscapacidadIMPL;
import CONTROLADOR.DAOSVMascotaCabinaIMPL;
import CONTROLADOR.DAOSVMascotaIMPL;
import Interfaces.DAOSVDiscapacidad;
import Interfaces.DAOSVMascota;
import Interfaces.DAOSVMascotaCabina;
import MODELS.ServicioMascota;
import MODELS.ServicioMascotaCabina;
import MODELS.ServiciosEspeciales;
import MODELS.Vuelos;
import VIEW1.Dashboard;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Samsung
 */
public class VerSVEspeciales extends javax.swing.JPanel {
    public Vuelos vuelo;
    /**
     * Creates new form Principal
     */
    public VerSVEspeciales() {
        initComponents();
        tablaSV.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lbSV = new javax.swing.JLabel();
        lb_back = new javax.swing.JLabel();
        lbSVrellenar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSV = new javax.swing.JTable();
        bt_borrarSV = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(710, 403));
        setPreferredSize(new java.awt.Dimension(710, 403));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(710, 403));
        bg.setPreferredSize(new java.awt.Dimension(710, 390));

        lbSV.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        lbSV.setForeground(new java.awt.Color(0, 0, 0));
        lbSV.setText("Servicios Especiales ");

        lb_back.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        lb_back.setForeground(new java.awt.Color(191, 191, 191));
        lb_back.setText("<<<");
        lb_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_backMouseExited(evt);
            }
        });

        lbSVrellenar.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        lbSVrellenar.setForeground(new java.awt.Color(0, 0, 0));
        lbSVrellenar.setText("Vuelo : ");

        tablaSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Servicio", "Id Pasajero", "Servicio", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaSV);
        if (tablaSV.getColumnModel().getColumnCount() > 0) {
            tablaSV.getColumnModel().getColumn(0).setMinWidth(20);
            tablaSV.getColumnModel().getColumn(0).setMaxWidth(100);
            tablaSV.getColumnModel().getColumn(1).setMinWidth(20);
            tablaSV.getColumnModel().getColumn(1).setMaxWidth(100);
            tablaSV.getColumnModel().getColumn(2).setMinWidth(170);
            tablaSV.getColumnModel().getColumn(2).setMaxWidth(300);
            tablaSV.getColumnModel().getColumn(3).setMinWidth(300);
        }

        bt_borrarSV.setText("Borrar");
        bt_borrarSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_borrarSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbSV, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbSVrellenar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_back, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bt_borrarSV)))
                        .addGap(46, 46, 46))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSVrellenar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lb_back, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bt_borrarSV)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void listarSVs(int idVU){
        DAOSVDiscapacidad daoDIS = new DAOSVDiscapacidadIMPL();
        DAOSVMascota daoMA = new DAOSVMascotaIMPL();
        DAOSVMascotaCabina daoMAC = new DAOSVMascotaCabinaIMPL();
        
        try {
           List<ServiciosEspeciales> listSVesp = daoDIS.listarForVU(idVU);
           List<ServicioMascota> listSVma = daoMA.listarForVU(idVU);
           List<ServicioMascotaCabina> listSVmac = daoMAC.listarForVU(idVU);
       
            DefaultTableModel model = (DefaultTableModel) tablaSV.getModel();
            model.setRowCount(0);
            listSVesp.forEach((svESP)->model.addRow(new Object[]{svESP.getId(), svESP.getIdPasajero(), svESP.getTipo(), svESP.getDescripcion()}));
            listSVma.forEach((svESP)->model.addRow(new Object[]{svESP.getId(), svESP.getIdPasajero(), svESP.getTipo(), svESP.getDescripcion()}));
            listSVmac.forEach((svESP)->model.addRow(new Object[]{svESP.getId(), svESP.getIdPasajero(), svESP.getTipo(), svESP.getDescripcion()}));

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
        
    private void lb_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseClicked
    }//GEN-LAST:event_lb_backMouseClicked

    private void lb_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseEntered
        lb_back.setForeground(Color.BLACK);
    }//GEN-LAST:event_lb_backMouseEntered

    private void lb_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_backMouseExited
        lb_back.setForeground(new Color(191,191,191));
    }//GEN-LAST:event_lb_backMouseExited

    private void bt_borrarSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_borrarSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_borrarSVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel bg;
    public javax.swing.JButton bt_borrarSV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbSV;
    public javax.swing.JLabel lbSVrellenar;
    public javax.swing.JLabel lb_back;
    public javax.swing.JTable tablaSV;
    // End of variables declaration//GEN-END:variables
}
